name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push to output branch

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for contribution graph

      - name: Generate Pac-Man graph
        uses: yonnyz/pacman-contribution-graph@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout --orphan output
          git reset
          git add pacman-contribution-graph.svg pacman-contribution-graph-dark.svg
          git commit -m "Generate Pac-Man Contribution Graph"
          git push -f origin output
