name: 🐍 Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: aaliyanexe
          outputs: |
            dist/snake.svg

      - name: Commit and push snake.svg
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch
          git checkout main
          mkdir -p assets
          cp dist/snake.svg assets/
          git add assets/snake.svg
          git commit -m "Update Snake Contribution Graph"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
