name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Pac-Man graph
        uses: lowlighter/pacman-graph@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: pacman.svg
          color: yellow
          background: 0b1a2d
          resolution: 1.5

      - name: Upload SVG
        run: |
          mkdir -p public
          mv pacman.svg public/
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git checkout --orphan output
          git reset
          mv public/* .
          git add pacman.svg
          git commit -m "Generate Pac-Man Contribution Graph"
          git push -f origin output
